### ISSUE TITLE
Can not login because the google_oauth2 provider has been removed.

### ISSUE THREAD

**Issue by dozen** [ryotarai/waker#57]
related to #47.

The default redirect destination when not logging in is /auth/google_oauth2, but because google_oauth2 provider was removed in #47, so can not login.

Is it possible to revive google_oauth2 provider?

```diff
diff --git a/config/initializers/omniauth.rb b/config/initializers/omniauth.rb
index 8d2cabb..fe13329 100644
--- a/config/initializers/omniauth.rb
+++ b/config/initializers/omniauth.rb
@@ -6,5 +6,6 @@ Rails.application.config.middleware.use OmniAuth::Builder do
   config.merge(scope: 'userinfo.profile,userinfo.email,calendar',
                name: 'google_oauth2_with_calendar',
                access_type: 'offline', approval_prompt: 'force', prompt: 'consent')
+  provider :google_oauth2, ENV["GOOGLE_CLIENT_ID"], ENV["GOOGLE_CLIENT_SECRET"], config
 end
 OmniAuth.config.logger = Rails.logger
```

**Comment by pyama86** [comment]
これお話した時消えてるっていう話でしたけど、消えてなくないです？
https://github.com/ryotarai/waker/blob/master/config/initializers/omniauth.rb#L5

いま普通に動いてoAuth通ってしまいました。。。

**Comment by dozen** [comment]
https://github.com/ryotarai/waker/issues/57#issuecomment-457828199

それは `/auth/google_oauth2_with_calendar` のことではないでしょうか。こちらは消えていないと思いますが、 waker にはもともと `/auth/google_oauth2` と `/auth/google_oauth2_with_calendar` という2つのOAuth認証用のエンドポイントが生えていました。

https://github.com/ryotarai/waker/blob/f66250d8825413aa1f2ecc46419231bed6e1ec57/config/initializers/omniauth.rb#L5-L7

上の方が `/auth/google_oauth2_with_calendar`
```ruby
 provider :google_oauth2, ENV["GOOGLE_CLIENT_ID"], ENV["GOOGLE_CLIENT_SECRET"], 
   config.merge(scope: 'userinfo.email,calendar', name: 'google_oauth2_with_calendar') 
```

下の方が `/auth/google_oauth2`
```ruby
 provider :google_oauth2, ENV["GOOGLE_CLIENT_ID"], ENV["GOOGLE_CLIENT_SECRET"], config 
```

今回報告させていただいているのは、 `/auth/google_oauth2` の方です。 
弊社では calendar の scope を全員に許可する必要がなかったのと、waker はログインしてないときはデフォルトで [/auth/google_oauth2 に飛ばすようになってる](https://github.com/ryotarai/waker/blob/master/app/controllers/application_controller.rb#L16
) ので、 基本的に `google_oauth2` の方を使ってもらうようにしていましたが、今回最新版にしてみたら消えていてログインできなくなっていたという感じです…。

ユーザを作ったときに踏んだエンドポイントによって認証 provider が `google_oauth2` か `google_oauth2_with_calendar` に分かれてしまう（違うユーザになってしまう）のと、calendar の scope を許可する必要のない人についてはこれまで通り provider: google_oauth2 で認証させたいので、 /auth/google_oauth2 を復活していただけないでしょうか、という相談でした。


> いま普通に動いてoAuth通ってしまいました。。。

むむ…。
私が master (fda64423823e4134511bb33a84c3fccf163a04d2) で試した場合ですと `/` にアクセスしたあと `/auth/google_oauth2` に飛ばされ、 404 になってしまうというところまで再現しているのですが…。。

![image](https://user-images.githubusercontent.com/802038/51820896-8f313780-231a-11e9-940c-b38ab7aceb4a.png)

**Comment by pyama86** [comment]
僕が普通に使えてるのは、あれですねoauthの戻りのURLを書き換えてるからとかなのかもしれないです。おっしゃることわかったのでPR投げときます。

**Comment by dozen** [comment]
ありがとうございます！
